title: Russell Laffitte was the former CEO of Palmetto State Bank, part of a multi-generational family associated with PSB, and also enabler for Alex Murdaugh to conduct his financial crimes of robbing clients of their due settlements. 
author:
  name: Ralph Hightower 
  email: ralph.hightower@gmail.com
  #street_address:
  city: Chapin
  state: South Carolina
  zip_code: 29036
  country: United States of America
  #phone:
description: > # this means to ignore newlines until "show_excerpts:"
  Greg Alexander is Sheriff Roscoe P Coltrane of Yemassee County and "fixer" for former attorney, now convicted felon, Alex Murdaugh. 
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %I:%M:%S.%L %p %Z" # "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: RalphHightower 
    github:  RalphHightower
    # devto: jekyll
    # dribbble: jekyll
    facebook: RalphHightower 
    flickr:   RalphHightower
    googledev: RalphHightower
    # instagram: jekyll
    linkedin: RalphHightower 
    stackoverflow: 26315139/ralph-hightower
    # pinterest: jekyll
    youtube: RalphHightower 
    youtube_channel: UCnaJ74ytj6_bCsk-xFHgaYw
    youtube_channel_name: RalphHightower
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
    # google_scholar_id: qc6CJjYAAAAJ
    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
    # GitLab instances
    gitlab:
    - username: RalphHightower
    - username: PermanentVacations
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - "jekyll-feed"
 - "jekyll-seo-tag"
 - "jekyll-last-modified-at"
# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%d %I:%M:%S.%L %p %Z' #'%d-%b-%y'

repository: "RalphHightower/MurdaughPICGregAlexander"
